# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HADemo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
#
#  Use for KinCony's KC868-Hx Relay controller TCP Socket-->MQTT
#

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HADemo(object):
    def setupUi(self, HADemo):
        HADemo.setObjectName("HADemo")
        HADemo.resize(1274, 469)
        self.centralwidget = QtWidgets.QWidget(HADemo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gbInput = QtWidgets.QGroupBox(self.centralwidget)
        self.gbInput.setObjectName("gbInput")
        self.glInput = QtWidgets.QGridLayout(self.gbInput)
        self.glInput.setObjectName("glInput")
        self.gridLayout.addWidget(self.gbInput, 1, 2, 1, 1)
        self.gbSettings = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSettings.setMaximumSize(QtCore.QSize(400, 200))
        self.gbSettings.setObjectName("gbSettings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbSettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gbDevice = QtWidgets.QGroupBox(self.gbSettings)
        self.gbDevice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gbDevice.setObjectName("gbDevice")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbDevice)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.gbDevice)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.leDeviceIp = QtWidgets.QLineEdit(self.gbDevice)
        self.leDeviceIp.setObjectName("leDeviceIp")
        self.gridLayout_4.addWidget(self.leDeviceIp, 1, 0, 1, 1)
        self.leDevicePort = QtWidgets.QLineEdit(self.gbDevice)
        self.leDevicePort.setObjectName("leDevicePort")
        self.gridLayout_4.addWidget(self.leDevicePort, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbDevice)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbDevice, 0, 0, 1, 1)
        self.gbMQTT = QtWidgets.QGroupBox(self.gbSettings)
        self.gbMQTT.setObjectName("gbMQTT")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbMQTT)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.leMQTTIp = QtWidgets.QLineEdit(self.gbMQTT)
        self.leMQTTIp.setObjectName("leMQTTIp")
        self.gridLayout_3.addWidget(self.leMQTTIp, 1, 0, 2, 2)
        self.leMQTTPort = QtWidgets.QLineEdit(self.gbMQTT)
        self.leMQTTPort.setObjectName("leMQTTPort")
        self.gridLayout_3.addWidget(self.leMQTTPort, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gbMQTT)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbMQTT)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbMQTT, 0, 1, 1, 1)
        self.pbConnect = QtWidgets.QPushButton(self.gbSettings)
        self.pbConnect.setObjectName("pbConnect")
        self.gridLayout_2.addWidget(self.pbConnect, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.gbSettings, 1, 0, 1, 1)
        self.gbDeviceType = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDeviceType.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gbDeviceType.setObjectName("gbDeviceType")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbDeviceType)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rbH16 = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbH16.setObjectName("rbH16")
        self.gridLayout_5.addWidget(self.rbH16, 4, 1, 1, 1)
        self.rbH4 = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbH4.setObjectName("rbH4")
        self.gridLayout_5.addWidget(self.rbH4, 0, 1, 1, 1)
        self.rbH8 = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbH8.setObjectName("rbH8")
        self.gridLayout_5.addWidget(self.rbH8, 4, 0, 1, 1)
        self.rbH32 = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbH32.setObjectName("rbH32")
        self.gridLayout_5.addWidget(self.rbH32, 7, 0, 1, 1)
        self.rbH2 = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbH2.setObjectName("rbH2")
        self.gridLayout_5.addWidget(self.rbH2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbDeviceType, 1, 1, 1, 1)
        self.gbOutput = QtWidgets.QGroupBox(self.centralwidget)
        self.gbOutput.setObjectName("gbOutput")
        self.glOutput = QtWidgets.QGridLayout(self.gbOutput)
        self.glOutput.setObjectName("glOutput")
        self.gb1 = QtWidgets.QGroupBox(self.gbOutput)
        self.gb1.setObjectName("gb1")
        self.glOutput.addWidget(self.gb1, 0, 0, 1, 1)
        self.gb2 = QtWidgets.QGroupBox(self.gbOutput)
        self.gb2.setObjectName("gb2")
        self.glOutput.addWidget(self.gb2, 0, 1, 1, 1)
        self.gb3 = QtWidgets.QGroupBox(self.gbOutput)
        self.gb3.setObjectName("gb3")
        self.glOutput.addWidget(self.gb3, 0, 2, 1, 1)
        self.gb4 = QtWidgets.QGroupBox(self.gbOutput)
        self.gb4.setObjectName("gb4")
        self.glOutput.addWidget(self.gb4, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.gbOutput, 2, 0, 1, 3)
        self.pteCommand = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pteCommand.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pteCommand.setObjectName("pteCommand")
        self.gridLayout.addWidget(self.pteCommand, 1, 3, 2, 1)
        HADemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HADemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1274, 23))
        self.menubar.setObjectName("menubar")
        HADemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HADemo)
        self.statusbar.setObjectName("statusbar")
        HADemo.setStatusBar(self.statusbar)

        self.retranslateUi(HADemo)
        self.pbConnect.clicked.connect(self.connect)
        self.rbH2.clicked.connect(self.changeDeviceType)
        self.rbH4.clicked.connect(self.changeDeviceType)
        self.rbH8.clicked.connect(self.changeDeviceType)
        self.rbH16.clicked.connect(self.changeDeviceType)
        self.rbH32.clicked.connect(self.changeDeviceType)
        QtCore.QMetaObject.connectSlotsByName(HADemo)

    def retranslateUi(self, HADemo):
        _translate = QtCore.QCoreApplication.translate
        HADemo.setWindowTitle(_translate("HADemo", "Home assistant Demo For KC868-Hx Controller  Made by KinCony"))
        self.gbInput.setTitle(_translate("HADemo", "Input"))
        self.gbSettings.setTitle(_translate("HADemo", "Connect"))
        self.gbDevice.setTitle(_translate("HADemo", "Device"))
        self.label.setText(_translate("HADemo", "IP/Domain"))
        self.label_2.setText(_translate("HADemo", "Port"))
        self.gbMQTT.setTitle(_translate("HADemo", "MQTT"))
        self.label_4.setText(_translate("HADemo", "Port"))
        self.label_3.setText(_translate("HADemo", "IP/Domain"))
        self.pbConnect.setText(_translate("HADemo", "Connect"))
        self.gbDeviceType.setTitle(_translate("HADemo", "Device Type"))
        self.rbH16.setText(_translate("HADemo", "KC868-H16"))
        self.rbH4.setText(_translate("HADemo", "KC868-H4"))
        self.rbH8.setText(_translate("HADemo", "KC868-H8"))
        self.rbH32.setText(_translate("HADemo", "KC868-H32"))
        self.rbH2.setText(_translate("HADemo", "KC868-H2"))
        self.gbOutput.setTitle(_translate("HADemo", "Output"))
        self.gb1.setTitle(_translate("HADemo", "Group 1"))
        self.gb2.setTitle(_translate("HADemo", "Group 2"))
        self.gb3.setTitle(_translate("HADemo", "Group 3"))
        self.gb4.setTitle(_translate("HADemo", "Group 4"))
